apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-custom
spec:
  selector:
    matchLabels:
      app: prometheus-custom
  template:
    metadata:
      labels:
        app: prometheus-custom
    spec:
      containers:
        - name: prometheus-custom
          image: hoang1712/prometheus-custom
          env:
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              value: "mysqlpw"
            - name: DB_NAME
              value: "my_db"
            - name: DB_HOST
              value: "localhost"
            - name: DB_PORT
              value: '49153'
            - name: PROMETHEUS_URL
              value: "localhost:8428"
            - name: TIME_START
              value: "17:00"
            - name: TIME_ZONE
              value: "Asia/Ho_Chi_Minh"
